### PR TITLE
Support `spy.on` with nullish prototype

### LINKED ISSUE #117: `spy.on` doesn't work with nullish prototype
I've noticed that if you do something like
```js
const object = Object.create(null);
object.method = function() {};
chai.spy.on(object, 'method');
```
it will throw an error because it uses
```js
object.hasOwnProperty(methodName);
```

This can be fixed easily by changing it to
```js
Object.hasOwnProperty.call(object, methodName);
```

I will file a PR for this.

### Context

I've encountered the issue in the context of migrating to Vue 3 and using [@vue/test-utils](https://www.npmjs.com/package/@vue/test-utils). Apparently if you mount a component like
```js
import { mount } from '@vue/test-utils';
let { vm } = mount(Component);
```
then `vm` is an object with `null` as its prototype. If you then want to spy on some of its methods with `chai.spy.on`, it throws the error above.

### PR DESCRIPTION
**Pull request by sebamarynissen**
Fixes #117.

### CODE REVIEW

**Review by keithamus — APPROVED** [review]
LGTM

**Comment by keithamus** [comment]
Looks like travis CI is no longer working. I'll find some time to port to GitHub Actions and then get this merged, it might be a while though.

**Comment by sebamarynissen** [comment]
I can have a look at writing a GitHub action for it if you want, at least for running the tests on every PR. I don't have any experience with writing an action for publishing to npm, but I'll see what I can do. This should happen for every commit on `master` right? Is the version increased manually or should this happen in an action as well?

**Comment by keithamus** [comment]
I'd like to move Chai packages to a model I use at work, which is that we have a build step that simply runs `npm it` (e.g. here: https://github.com/github/relative-time-element/blob/main/.github/workflows/test.yml) and an action which runs whenever we publish a release via the GitHub UI, which publishes the package to the various registries (e.g. here: https://github.com/github/relative-time-element/blob/main/.github/workflows/publish.yml).

If you'd like to try and add those in a PR that'd be a great contribution that would be much appreciated!

**Comment by sebamarynissen** [comment]
@keithamus I created another PR that sets up GitHub actions for CI and publishing (#119). The PR was created off the master branch, so it does not include the changes from this PR yet. I propose to merge #119 first, and then we can merge this one, perhaps after a rebase.

**Comment by sebamarynissen** [comment]
@keithamus Is there anything that prevents releasing this on npm? I'm migrating a large codebase to Vue 3 at the moment and I'm using my own fork in `package.json` for it now
```json
{
  "dependencies": {
    "chai-spies": "github:sebamarynissen/chai-spies#feature/nullish-prototype",
  }
}
```
but it obviously would be nicer to be able to just use `chai-spies` from npm.

Let me know if there's anything I can do to help if needed!

**Comment by keithamus** [comment]
@sebamarynissen v1.1.0 has been released. Thanks!

**Pull request merged**
