### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by stalniy**
* documentation
* package.json

### CODE REVIEW

**Comment by keithamus** [comment]
@stalniy as part of this I think we should also drop Node < 4 from the package.json, and no longer support it. Thoughts?

**Comment by stalniy** [comment]
@keithamus this was done in #91

**Comment by keithamus** [comment]
Yup 😆 just saw that and merged.

**Comment by keithamus** [comment]
If you rebase this against master, the tests will pass and I will merge 👍

**Comment by stalniy** [comment]
Done! lets merge this :)

**Comment by stalniy** [comment]
@keithamus what do we need to do next to publish 1.0.0 on npm?

**Comment by keithamus** [comment]
@stalniy could you please add some release notes to https://github.com/chaijs/chai-spies/releases/edit/untagged-c4a7ec2f780e17401aef and then hit `Publish` - CI will take care of the rest.

**Comment by stalniy** [comment]
Cool! @keithamus what do you think about merging #93  in 1.0.0 as well?

**Comment by keithamus** [comment]
Ideally the format should be:

```
General release notes go here

# Breaking Changes
* <feat|fix>: Something breaking here #PRref (#IssueRef, @person-who-worked-on-it)

# Bug Fixes
* <feat|fix>: Something breaking here #PRref (#IssueRef, @person-who-worked-on-it)

# Docs
* <feat|fix>: Something breaking here #PRref (#IssueRef, @person-who-worked-on-it)
```

**Comment by stalniy** [comment]
Sorry @keithamus , missed your last message. I will change the format. Do you use some a tool to generate release notes?

**Comment by stalniy** [comment]
Also `npm i chai-spies@1.0.0` fails and `npm i chai-spies@latest` installs 0.7.1 version. Are there some issues with CI pipeline or you decided to postpone release to fix release notes format?

**Comment by stalniy** [comment]
@keithamus updated release notes according to recommended format, also added `Bug Fixes` section. Could you please review draft, publish if everything is ok and make sure CI build updated version on npm?

**Comment by keithamus** [comment]
I've gone ahead and manually published chai-spies@1.0.0 - it looks like it didnt publish on CI, I'll get around to fixing that later.

**Pull request merged**
